@startuml
title ESI-SPORT Use Cases

!define DARKBLUE
!include styles.puml

left to right direction


' actors definition
actor admin as "Administrateur"
actor user as "Visiteur"
actor editor as "Editeur"
actor supervisor as "Superviseur"
actor sportMaster as "Gestionnaire Sportif"

rectangle Esi-Sport {
    ' use cases definition
    usecase consultMatches as "Consulter Matchs"
    usecase consultClassement as "Consulter Classement InterEcole"
    usecase searchBlog as "Rechercher Articles Blog"
    usecase commentBlog as "Commenter Article Blog"
    usecase editBlog as "Créer articles Blog"
    usecase publishBlog as "Publier articles Blog"
    usecase manageUser as "Gérer Utilisateurs"
    usecase manageSports as "Gérer Matchs"
    usecase manageClubs as "Gérer Clubs"

    ' actors relations
    user -- (consultMatches)
    user -- (searchBlog)
    user -- (commentBlog)
    user -- (consultClassement)

    (manageUser) -- admin
    (manageSports) -- sportMaster
    (manageClubs) -- sportMaster
    (editBlog) -- editor
    (publishBlog) -- supervisor

    (publishBlog) .> (editBlog) : <<include>>

    supervisor <|- admin
    admin -|> sportMaster

}

@enduml